    



from enum import Enum


class AddNoiseMode(Enum):
    NoNoise: ...
    Synonym: ...
    Paraphrase: ...

class ApiModel(Enum):
    Gpt5: ...
    Gpt5Mini: ...
    Gpt5Nano: ...
    DeepSeek: ...
    Llama3_1_8B: ...
    Llama3_1_70B: ...

class Language(Enum):
    Chinese: ...
    Hindi: ...

class LocalModel(Enum):
    Granite4_0HTiny: ...
    Granite4_0HSmall: ...
    Qwen3_8B: ...
    Qwen3_14B: ...
    Qwen3_30bA3b: ...
    Qwen3_32B: ...
    Qwen3Next80bA3b: ...
    Llama3_1_8B: ...
    Llama3_1_70B: ...

class Model:
    Api = ApiModel
    Local = LocalModel

class TranslateOption(Enum):
    FullyTranslated: ...
    FullyTranslatedPromptTranslate: ...
    PartiallyTranslated: ...
    FullyTranslatedPreTranslate: ...
    FullyTranslatedPostTranslate: ...

class TranslateMode_Translated:
    def __new__(cls, *, language: Language, option: TranslateOption) -> TranslateMode: ...

class TranslateMode_NotTranslated:
    def __new__(cls) -> TranslateMode: ...

class TranslateMode:
    Translated = TranslateMode_Translated
    NotTranslated = TranslateMode_NotTranslated

class ToolExperiment:
    def __new__(cls, translate_mode: TranslateMode, add_noise_mode: AddNoiseMode) -> ToolExperiment: ...

class ToolConfig:
    def __new__(cls, model: Model, experiment_configs: list[ToolExperiment]) -> ToolConfig: ...

class JudgeExperiment(Enum):
    PreferenceDirect: ...
    Perplexity: ...

class JudgeConfig:
    def __new__(cls, model: LocalModel, lang1: str, lang2: str, experiment: JudgeExperiment) -> JudgeConfig: ...