#!/usr/bin/env python3
"""
Compare tool formats generated by Rust and Python implementations.

This script loads the output files from both implementations and
identifies any differences in the generated tool definitions.
"""

import json
from pathlib import Path
from deepdiff import DeepDiff


def load_json_file(filepath):
    """Load JSON file"""
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)


def compare_tool_formats():
    """Compare tool formats from Rust and Python implementations"""
    rust_output = "tool_format_comparison_rust.json"
    python_output = "tool_format_comparison_python.json"

    print("Loading output files...")
    rust_data = load_json_file(rust_output)
    python_data = load_json_file(python_output)

    print(f"Rust entries: {len(rust_data)}")
    print(f"Python entries: {len(python_data)}")
    print()

    if len(rust_data) != len(python_data):
        print(f"WARNING: Different number of entries!")
        print()

    # Compare each entry
    differences_found = False
    entries_with_diffs = []

    for i in range(min(len(rust_data), len(python_data))):
        rust_entry = rust_data[i]
        python_entry = python_data[i]

        # Check if IDs match
        if rust_entry["id"] != python_entry["id"]:
            print(f"Entry {i}: ID mismatch!")
            print(f"  Rust: {rust_entry['id']}")
            print(f"  Python: {python_entry['id']}")
            continue

        entry_id = rust_entry["id"]

        # Compare tools
        diff = DeepDiff(rust_entry["tools"], python_entry["tools"], ignore_order=False)

        if diff:
            differences_found = True
            entries_with_diffs.append(entry_id)
            print(f"Entry {entry_id}: Differences found in tools")
            print(f"  {diff}")
            print()

    if not differences_found:
        print("✓ No differences found! Both implementations generate identical tool formats.")
    else:
        print(f"\n✗ Differences found in {len(entries_with_diffs)} entries:")
        for entry_id in entries_with_diffs:
            print(f"  - {entry_id}")

    # Show sample outputs
    print("\n" + "="*80)
    print("Sample output (first entry):")
    print("="*80)
    print("\nRust implementation:")
    print(json.dumps(rust_data[0]["tools"][0], indent=2))
    print("\nPython implementation:")
    print(json.dumps(python_data[0]["tools"][0], indent=2))


if __name__ == "__main__":
    try:
        compare_tool_formats()
    except ImportError:
        print("Error: deepdiff module not found.")
        print("Installing deepdiff...")
        import subprocess
        subprocess.check_call(["pip", "install", "deepdiff"])
        print("Please run the script again.")
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
