
from typing import Any
import importlib
import importlib.util
import os


import json
def load_config_from_file(config_file_path: str, config_var_name: str):
    """
    Load the 'config' list from a specified Python file.

    Args:
        config_file_path: Path to the Python file containing config

    Returns:
        The config list from the specified file
    """
    # Convert to absolute path if relative
    config_file_path = os.path.abspath(config_file_path)

    if not os.path.exists(config_file_path):
        raise FileNotFoundError(f"Config file not found: {config_file_path}")

    # Load the module dynamically
    spec = importlib.util.spec_from_file_location("custom_config", config_file_path)
    config_module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(config_module)

    if not hasattr(config_module, config_var_name):
        raise AttributeError(f"Config file {config_file_path} does not contain a '{config_var_name}' variable")

    return getattr(config_module, config_var_name)

def load_json_lines_from_file(file_path) -> list[Any]:
    """Load json lines from a JSONL file."""
    entries = []
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                entries.append(json.loads(line))
    return entries


def combine_entries_to_pairs(entries1, entries2, lang1, lang2):
    """
    Combine two lists of entries into pairs by matching indices.

    Args:
        entries1: List of entries for answer1 (lang1)
        entries2: List of entries for answer2 (lang2)
        lang1: Language code for answer1
        lang2: Language code for answer2

    Returns:
        List of pairs with structure:
        {
            'index': int,
            'question': str,
            'answer1': str,
            'answer2': str,
            'lang1': str,
            'lang2': str,
            'is_correct1': bool,
            'is_correct2': bool,
            'subject': str,
        }
    """
    # Index entries by their index field
    entries1_by_index = {e['index']: e for e in entries1}
    entries2_by_index = {e['index']: e for e in entries2}

    # Find common indices
    common_indices = set(entries1_by_index.keys()) & set(entries2_by_index.keys())

    pairs = []
    for idx in sorted(common_indices):
        e1 = entries1_by_index[idx]
        e2 = entries2_by_index[idx]

        pair = {
            'index': idx,
            'question': e1['question'],
            'answer1': e1['answer'],
            'answer2': e2['answer'],
            'lang1': lang1,
            'lang2': lang2,
            'is_correct1': e1['is_correct'],
            'is_correct2': e2['is_correct'],
            'subject': e1.get('subject', ''),
        }
        pairs.append(pair)

    return pairs

def get_model_directory_safe_name(model_name: str) -> str:
    """Convert model name to a filesystem-safe directory name."""
    return model_name.replace("/", "-").replace(":", "-")

def language_abbreviation_to_name(abbreviation: str) -> str:
    """
    Map language abbreviation to full language name.

    Args:
        abbreviation: Language code (e.g., 'en', 'zh_cn', 'fr')

    Returns:
        Full language name (e.g., 'English', 'Chinese', 'French')
    """
    lang_map = {
        'en': 'English',
        'fr': 'French',
        'de': 'German',
        'es': 'Spanish',
        'it': 'Italian',
        'pt': 'Portuguese',
        'zh_cn': 'Chinese',
        'ja': 'Japanese',
        'ko': 'Korean',
    }
    return lang_map.get(abbreviation.lower(), abbreviation)




def trim_forward_prompt_and_get_char_mask(forward_prompt: str):
    """
    Trim <answer> tags from a forward prompt and create a character-level mask.

    This function should be applied to the complete formatted prompt (including both
    user and assistant messages) that will be passed to the model's forward function.
    The resulting mask will align with the tokens generated by tokenizing this prompt.

    Args:
        forward_prompt: str, the complete formatted prompt with <answer> tags
                       (e.g., result of tokenizer.apply_chat_template with tokenize=False)

    Returns:
        tuple: (trimmed_prompt, char_mask) where:
            - trimmed_prompt: str, prompt with <answer> tags removed
            - char_mask: list of bool, True for character positions that were inside <answer> tags
    """
    import re

    # Pattern to match <answer>...</answer>
    pattern = r'<answer>(.*?)</answer>'

    # Track character positions
    char_positions = []  # List of (char, is_answer)
    last_end = 0

    for match in re.finditer(pattern, forward_prompt):
        # Add non-answer text before this match
        before_text = forward_prompt[last_end:match.start()]
        for char in before_text:
            char_positions.append((char, False))

        # Add answer text
        answer_text = match.group(1)
        for char in answer_text:
            char_positions.append((char, True))

        last_end = match.end()

    # Add remaining text after last match
    remaining_text = forward_prompt[last_end:]
    for char in remaining_text:
        char_positions.append((char, False))

    # Build trimmed prompt and char mask
    trimmed_prompt = ''.join(char for char, _ in char_positions)
    char_mask = [is_answer for _, is_answer in char_positions]

    return trimmed_prompt, char_mask


def trim_styled_response_and_get_char_mask(styled_response: str):
    """
    Trim <answer> tags from a styled response and create a character-level mask.

    DEPRECATED: Use trim_forward_prompt_and_get_char_mask instead, which works on
    the full formatted prompt rather than just the response portion.

    Args:
        styled_response: str, the response with <answer> tags (e.g., "The answer is <answer>42</answer>.")

    Returns:
        tuple: (trimmed_response, char_mask) where:
            - trimmed_response: str, response with <answer> tags removed
            - char_mask: list of bool, True for character positions that were inside <answer> tags
    """
    return trim_forward_prompt_and_get_char_mask(styled_response)


def convert_char_mask_to_token_mask(trimmed_response: str, char_mask: list, tokenizer: Any, debug: bool = False):
    """
    Convert a character-level mask to a token-level mask.

    Args:
        trimmed_response: str, the response text (without tags)
        char_mask: list of bool, True for character positions that should be masked
        tokenizer: Tokenizer instance
        debug: bool, if True, print debug information about masked tokens

    Returns:
        list of bool: token-level mask, True for tokens that were inside masked characters
    """
    # Tokenize the trimmed response
    tokens = tokenizer(trimmed_response, add_special_tokens=False)
    input_ids = tokens.input_ids

    # Create token mask by checking which tokens correspond to masked characters
    # We'll mark a token as "masked" if any of its characters were masked
    token_mask = []
    masked_token_ids = []  # Store token IDs of masked tokens for debugging

    # Get character spans for each token
    char_idx = 0
    for token_id in input_ids:
        token_text = tokenizer.decode([token_id], skip_special_tokens=False)
        token_len = len(token_text)

        # Check if any character in this token's span is masked
        is_masked_token = False
        for i in range(char_idx, min(char_idx + token_len, len(char_mask))):
            if i < len(char_mask) and char_mask[i]:
                is_masked_token = True
                break

        token_mask.append(is_masked_token)
        if is_masked_token:
            masked_token_ids.append(token_id)
        char_idx += token_len

    # Debug print if requested
    if debug:
        # Decode the masked tokens together to get the correct text
        masked_text = tokenizer.decode(masked_token_ids, skip_special_tokens=True)
        print(f"[DEBUG] trimmed_response: {repr(trimmed_response)}, char_mask length: {len(char_mask)}, token_mask length: {len(token_mask)}")
        print(f"[DEBUG] Masked: {sum(token_mask)}/{len(token_mask)} tokens | Text: {repr(masked_text)}")

    return token_mask


def parse_styled_response_to_mask(styled_response: str, tokenizer: Any):
    """
    Parse a styled response with <answer> tags and create a mask for highlighted tokens.

    This is a convenience function that combines trim_styled_response_and_get_char_mask
    and convert_char_mask_to_token_mask.

    Args:
        styled_response: str, the response with <answer> tags (e.g., "The answer is <answer>42</answer>.")
        tokenizer: Tokenizer instance

    Returns:
        tuple: (trimmed_response, answer_mask) where:
            - trimmed_response: str, response with <answer> tags removed
            - answer_mask: list of bool, True for tokens that were inside <answer> tags
    """
    trimmed_response, char_mask = trim_styled_response_and_get_char_mask(styled_response)
    token_mask = convert_char_mask_to_token_mask(trimmed_response, char_mask, tokenizer)
    return trimmed_response, token_mask


def calculate_perplexity_from_logits_with_mask(logits, input_ids, answer_mask):
    """
    Calculate perplexity for masked answer tokens.

    Args:
        logits: torch.Tensor of shape [seq_len, vocab_size]
        input_ids: List of token IDs
        answer_mask: List of bool, True for positions that should be included in perplexity calculation

    Returns:
        float: perplexity value
    """
    import torch
    import math

    # Assert relationships between parameters
    assert logits.shape[0] == len(input_ids), f"logits sequence length {logits.shape[0]} should equal input_ids length ({len(input_ids)})"
    assert len(answer_mask) == len(input_ids), f"answer_mask length {len(answer_mask)} should equal input_ids length ({len(input_ids)})"

    # Shift logits and labels for next-token prediction
    shift_logits = logits[:-1, :]  # All but last position
    shift_labels = torch.tensor(input_ids[1:])  # All but first position

    # Compute log probabilities
    log_probs = torch.nn.functional.log_softmax(shift_logits, dim=-1)

    # Gather log probs for the actual next tokens
    selected_log_probs = log_probs.gather(1, shift_labels.unsqueeze(-1)).squeeze(-1)

    # Apply mask (shift mask by 1 to align with next-token prediction)
    # answer_mask[i] indicates whether token i should be included
    # For next-token prediction, we want log_prob of predicting token i+1 from position i
    # So we use answer_mask[1:] to select which predictions to include
    assert len(answer_mask) >= 2, "answer_mask must have at least 2 elements to align with shifted predictions"
    shifted_mask = answer_mask[1:]  # Shift to align with next-token prediction
    mask_tensor = torch.tensor(shifted_mask, dtype=torch.bool)

    # Select only the log probs where mask is True
    masked_log_probs = selected_log_probs[mask_tensor]

    assert len(masked_log_probs) > 0, "No tokens were selected by the answer mask for perplexity calculation"
    
    # Calculate perplexity
    avg_log_prob = masked_log_probs.mean().item()
    perplexity = math.exp(-avg_log_prob)

    return perplexity


def calculate_perplexity_from_logits(logits, input_ids, answer, tokenizer):
    """
    Calculate perplexity for an answer using backward search to locate answer tokens.

    Args:
        logits: torch.Tensor of shape [seq_len, vocab_size]
        input_ids: List of token IDs
        answer: str, the answer text
        tokenizer: Tokenizer instance

    Returns:
        float: perplexity value
    """
    import torch
    import math

    # Tokenize the answer to get its token sequence
    answer_tokens = tokenizer(answer, add_special_tokens=False).input_ids

    # Search backwards for the answer token sequence
    answer_start = None
    for i in range(len(input_ids) - len(answer_tokens), -1, -1):
        if input_ids[i:i+len(answer_tokens)] == answer_tokens:
            answer_start = i
            break

    if answer_start is None:
        raise ValueError(f"Could not find answer tokens in input_ids by backward search")

    answer_end = answer_start + len(answer_tokens)

    # Shift logits and labels for next-token prediction
    shift_logits = logits[:-1, :]  # All but last position
    shift_labels = torch.tensor(input_ids[1:])  # All but first position

    # Compute log probabilities
    log_probs = torch.nn.functional.log_softmax(shift_logits, dim=-1)

    # Gather log probs for the actual next tokens
    selected_log_probs = log_probs.gather(1, shift_labels.unsqueeze(-1)).squeeze(-1)

    # Extract log probs for answer tokens (adjusting for shift)
    mask_start = answer_start - 1
    mask_end = answer_end - 1
    answer_log_probs = selected_log_probs[mask_start:mask_end]

    # Calculate perplexity
    if len(answer_log_probs) > 0:
        avg_log_prob = answer_log_probs.mean().item()
        perplexity = math.exp(-avg_log_prob)
    else:
        perplexity = float('inf')

    return perplexity